[tls]
  [tls.stores]
    [tls.stores.default]
      [tls.stores.default.defaultCertificate]
        certFile = "/certs/traefik.localhost+4.pem"
        keyFile = "/certs/traefik.localhost+4-key.pem"

  [[tls.certificates]]
    certFile = "/certs/traefik.localhost+4.pem"
    keyFile = "/certs/traefik.localhost+4-key.pem"
